version: 2

builds:
  - id: pf
    main: ./main.go
    binary: pf
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -extldflags '-static'

upx:
  - # Whether to enable it or not.
    #
    # Templates: allowed.
    enabled: true

    # Compress argument.
    # Valid options are from '1' (faster) to '9' (better), and 'best'.
    compress: best

    # Whether to try LZMA (slower).
    lzma: true